"""``sentinel config`` subcommand handlers — Phase 5 Task 8.

Per prod_imp.md § 7.5 the ``show`` path MUST NOT call
:meth:`SecretStr.get_secret_value`.  ``model_dump()`` returns a mix of
plain values and :class:`SecretStr` objects; the :func:`_coerce`
walker converts ``SecretStr`` -> ``str(secret)`` which yields
``'**********'`` (its ``__repr__``).  **Never** unwrap via
``.get_secret_value()`` — the redacted-token invariant is what the
L7 Phase 6 regression test checks.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from pydantic import SecretStr

from .exit_codes import EXIT_INVALID_ARGS, EXIT_IO_ERROR, EXIT_SUCCESS


_STARTER_CONFIG = """# Sentinel starter config — generated by `sentinel config init`.
# See prod_imp.md § 5.2 for the full precedence chain.

account_id = "123456789012"
region = "us-east-1"

[logging]
level = "INFO"
format = "human"

[network]
max_download_bytes = 10485760
timeout_seconds = 10
verify_tls = true

[pipeline]
max_self_check_retries = 3
fail_fast = false
"""


def _coerce(obj: Any) -> Any:
    """Recursively coerce a pydantic-dumped dict for TOML emission.

    SecretStr ``str()`` yields ``'**********'`` — NEVER call
    ``.get_secret_value()`` here (§ 7.5 / L7 Phase 6 regression).
    Also converts Path objects to strings and drops None values
    (tomli_w rejects None).
    """
    if isinstance(obj, SecretStr):
        return str(obj)  # "**********"
    if isinstance(obj, Path):
        return str(obj)
    if isinstance(obj, dict):
        out: dict[str, Any] = {}
        for k, v in obj.items():
            cv = _coerce(v)
            if cv is None:
                continue
            out[k] = cv
        return out
    if isinstance(obj, (list, tuple)):
        return [_coerce(v) for v in obj if v is not None]
    return obj


def _cmd_show(args: argparse.Namespace) -> int:
    from .config import get_settings

    try:
        import tomli_w
    except ImportError:
        print("Error: tomli-w is required for `config show`. Run `uv sync`.", file=sys.stderr)
        return EXIT_IO_ERROR

    settings = get_settings()
    dumped = settings.model_dump()
    coerced = _coerce(dumped)
    # tomli_w needs a top-level dict with no None leaves.
    try:
        text = tomli_w.dumps(coerced)
    except Exception as exc:  # noqa: BLE001 — diagnostic only.
        print(f"Error: failed to render config as TOML: {exc}", file=sys.stderr)
        return EXIT_IO_ERROR
    print(text, end="")
    return EXIT_SUCCESS


def _cmd_path(args: argparse.Namespace) -> int:
    from .config import (
        _project_local_path,
        _system_config_path,
        _user_config_path,
        get_settings,
    )

    # The resolved Settings carries the explicit --config override when one
    # was supplied; otherwise we report the *first* existing candidate from
    # the precedence chain, or the user-path default if nothing exists.
    settings = get_settings()
    if settings.config_path:
        print(str(settings.config_path))
        return EXIT_SUCCESS
    for p in (_project_local_path(), _user_config_path(), _system_config_path()):
        if p.is_file():
            print(str(p))
            return EXIT_SUCCESS
    # No file found — print the user-tier default so scripts can use it
    # as the target for `config init`.
    print(str(_user_config_path()))
    return EXIT_SUCCESS


def _cmd_init(args: argparse.Namespace) -> int:
    from .config import _user_config_path

    target = _user_config_path()
    if target.exists():
        print(f"Error: config already exists at {target}. Refusing to overwrite.", file=sys.stderr)
        return EXIT_INVALID_ARGS
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_STARTER_CONFIG, encoding="utf-8")
    print(f"Wrote starter config to {target}")
    return EXIT_SUCCESS


def cmd_config(args: argparse.Namespace) -> int:
    """Dispatch to ``show`` / ``path`` / ``init``."""
    sub = getattr(args, "config_cmd", None)
    if sub == "show":
        return _cmd_show(args)
    if sub == "path":
        return _cmd_path(args)
    if sub == "init":
        return _cmd_init(args)
    print(f"Unknown config subcommand: {sub!r}", file=sys.stderr)
    return EXIT_INVALID_ARGS


__all__ = ["cmd_config"]
